apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: blue # 초기에는 블루 환경으로 설정
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

